export default {
    MESSAGES: {
        USER_ALREADY_EXISTS: 'User already exists with this username or email',
        USER_NOT_AUTHORIZED: 'User not authorized for this role',
        USER_NOT_ALLOWED: 'User not allowed to do this task',
        SOMETHING_WENT_WRONG: 'Something went wrong! please try again',
        SELECT_REQUIRED_FIELDS: 'Select field-set of all the required fields',
        USERNAME_EMAIL_REQUIRED: 'Username or email is required',
        ONE_OF_THEM_REQUIRED: 'One of username and email is required',
        USER_NOT_EXIST: 'User does not exist with this username or email',
        INCORRECT_PASSWORD: 'Incorrect password',
        ALREADY_LOGGED_IN: 'You are already logged-in on this device',
        USER_NOT_EXIST_WITH_EMAIL: 'User does not exist with this email',
        AUTHENTICATION_FAILED: 'Authentication failed',
        INCORRECT_OTP: 'Incorrect OTP',
        USER_NOT_FOUND: 'User not found for this userId',
        TOKEN_IS_REQUIRED: 'Token is required',
        INVALID_TOKEN: 'Invalid token or signature',
        TOKEN_EXPIRED: 'Token has expired',
        SESSION_NOT_FOUND: 'Session not found for this sessionId',
        SESSION_EXPIRED: 'Session expired! please log-in again',
        NO_SESSION: 'User has no active session on this device',
        FOLLOWING_USER_NOT_EXIST: 'Following user does not exist with this userId',
        CANNOT_POST_ALBUM: 'You are not authorized to post an album',
        ALBUM_ALREADY_EXISTS: 'Album already exists for this artistId with this album-name',
        ARTIST_MUST_INCLUDED: 'This artist must be included in artists list',
        ONE_ARTIST_NOT_EXIST: 'One of the artists does not exist',
        ARTIST_NOT_EXIST: 'Artist does not exist with this artistId',
        DEFAULT_ARTIST: 'Default artist cannot be removed',
        ALBUM_NOT_FOUND: 'Album not found for this albumId',
        ALBUM_NOT_EXIST: 'Album does not exist with this artistId',
        SONG_ALREADY_EXISTS: 'Song already exists in this album',
        SONG_NOT_FOUND: 'Song not found for this songId',
        SONG_NOT_EXIST: 'Song does not exist with this artist',
        PLAYLIST_ALREADY_EXISTS: 'Playlist already exists for this userId with this playlist-name',
        PLAYLIST_NOT_FOUND: 'Playlist not found for this playlistId',
        PLAYLIST_NOT_EXIST: 'Playlist does not exist with this userId',
        PRIVATE_PLAYLIST: 'Cannot save private playlist to library',
        CATEGORY_NOT_EXIST: 'Category does not exist with this categoryId',
        ONLY_ADMIN_PLAYLISTS_ALLOWED: 'Only playlists created by admin are allowed',
        CANNOT_MODIFY_RESOURCE: 'You are not authorized to modify this resource',
        ALBUM_MUST_BE_EMPTY: 'Album must be empty to be deleted',
        ARTIST_NOT_DELETE: 'Artist is not allowed to delete account',
        ADMIN_NOT_DELETE: 'Admin is not allowed to delete account'
    },
    COLLECTIONS: {
        USER: 'User',
        SESSION: 'Session',
        FOLLOWER: 'Follower',
        LIBRARY: 'Library',
        SONG: 'Song',
        PLAYLIST: 'Playlist',
        ALBUM: 'Album',
        CATEGORY: 'Category'
    }
}
